/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/About.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Hero: typeof import('./src/components/Hero.vue')['default']
    IconAkarIconsUtensils: typeof import('~icons/akar-icons/utensils')['default']
    IconBiTelephone: typeof import('~icons/bi/telephone')['default']
    IconEpDessert: typeof import('~icons/ep/dessert')['default']
    IconFluentBowlSalad24Regular: typeof import('~icons/fluent/bowl-salad24-regular')['default']
    IconFluentDrinkBottle20Regular: typeof import('~icons/fluent/drink-bottle20-regular')['default']
    IconLucideCoffee: typeof import('~icons/lucide/coffee')['default']
    IconLucidePizza: typeof import('~icons/lucide/pizza')['default']
    IconLucideSalad: typeof import('~icons/lucide/salad')['default']
    IconMaterialSymbolsAddLocation: typeof import('~icons/material-symbols/add-location')['default']
    IconMaterialSymbolsCalendarMonthOutline: typeof import('~icons/material-symbols/calendar-month-outline')['default']
    IconMaterialSymbolsMapOutline: typeof import('~icons/material-symbols/map-outline')['default']
    IconMaterialSymbolsWineBarOutline: typeof import('~icons/material-symbols/wine-bar-outline')['default']
    IconMdiInstagram: typeof import('~icons/mdi/instagram')['default']
    IconMdiPasta: typeof import('~icons/mdi/pasta')['default']
    IconMynauiCocktail: typeof import('~icons/mynaui/cocktail')['default']
    IconStreamlineFoodDrinksWineBottleCookBottleWineDrinkCookingNutritionFood: typeof import('~icons/streamline/food-drinks-wine-bottle-cook-bottle-wine-drink-cooking-nutrition-food')['default']
    IconStreamlineFoodKitchenwareServingDomeCookToolDomeKitchenServingPaltterDishToolsFood: typeof import('~icons/streamline/food-kitchenware-serving-dome-cook-tool-dome-kitchen-serving-paltter-dish-tools-food')['default']
    IconStreamlineWine: typeof import('~icons/streamline/wine')['default']
    MdiInstagram: typeof import('./src/components/MdiInstagram.vue')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    MenuDrinks: typeof import('./src/components/MenuDrinks.vue')['default']
    MenuFood: typeof import('./src/components/MenuFood.vue')['default']
    MenuItems: typeof import('./src/components/MenuItems.vue')['default']
    MosaicDivider: typeof import('./src/components/MosaicDivider.vue')['default']
    NavigationBar: typeof import('./src/components/NavigationBar.vue')['default']
    NeonText: typeof import('./src/components/NeonText.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StoreInfo: typeof import('./src/components/StoreInfo.vue')['default']
    StoreInfoDiviver: typeof import('./src/components/StoreInfoDiviver.vue')['default']
  }
}
